
A = imread('images\four.png');
figure, imshow(A);
title("image A at time t");
B = imread('images\five.png');
figure, imshow(B);
title("image B at time t");
C = imsubtract(A,B);
figure, imshow(C);
title("image C");
D = imsubtract(B,A);
figure, imshow(D);
title("image D");
sharpA = imsharpen(A);
figure, imshow(sharpA);
title("sharpA image");
sharpB = imsharpen(B);
figure, imshow(sharpB);
title("sharpB image");
sharpC = imsubtract(sharpA,sharpB);
sharpC = imsharpen(sharpC);
figure, imshow(sharpC);
title("sharpC image");
subAD = imsubtract(A,D);
subAD_by_sharpB = imsubtract(subAD,sharpB);
h1 = fspecial('average');
outputAvg = imfilter(subAD_by_sharpB,h1);
figure, imshow(outputAvg);
title("Averaging filter");
h2 = fspecial('gaussian');
outputGau = imfilter(subAD_by_sharpB,h2);
figure, imshow(outputGau);
title("Gaussian filter");
h3 = fspecial('disk',2);
outputDisk = imfilter(subAD_by_sharpB,h3);
figure, imshow(outputDisk);
title("Disk filter");
h4 = fspecial('laplacian');
outputLap = imfilter(subAD_by_sharpB,h4);
figure, imshow(outputLap);
title("Laplacian filter");
h5 = fspecial('sobel');
outputSob = imfilter(subAD_by_sharpB,h5);
figure, imshow(outputSob);
title("Sobel filter");
h6 = fspecial('log');
outputLog = imfilter(subAD_by_sharpB,h6);
figure, imshow(outputLog);
title("Log filter");
h7 = fspecial('unsharp');
outputUns = imfilter(subAD_by_sharpB,h7);
figure, imshow(outputUns);
title("Unsharp filter");
h8 = fspecial('motion');
outputMot = imfilter(subAD_by_sharpB,h8);
figure, imshow(outputMot);
title("Motion filter");
subplot(2,3,1);
imshow(A);
subplot(2,3,2);
imshow(B);
subplot(2,3,3);
imshow(outputAvg);
subplot(2,3,4);
imshow(outputGau);
subplot(2,3,5);
imshow(outputDisk);
subplot(2,3,6);
imshow(outputLog);
